version: "3.9"
services:
  backend:
    build: ./backend
    container_name: finance_backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: finance_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: finance_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
